development:
  adapter: postgresql
  database: hack_weekend_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: hack_weekend_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: hack_weekend_production
  pool: 5
  timeout: 5000
